f = fopen('//Client/C$/Users/aasoni/Documents/NYU/Numerical Methods II/code/Final Project/data/surface.xyz');
A = fscanf(f,'%f %f %f');
A = reshape(A,3,[]);
m = 129; n = 282;
A = A';
X = A(1:n,1);
Y = A(1:n:m*n,2);
Z = reshape(A(:,3),n,m)';
disp('Ready to draw the mesh');
mesh(X,Y,Z);